name: flutter_game
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  bonfire: ^2.7.8
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/map/forestCliff_.png
    - assets/images/map/forest_.png
    - assets/images/map/pathDecoration_.png
    - assets/images/map/plainDecoration_0.png
    - assets/images/fHero.png
    - assets/images/map/Mapa1.json
    - assets/images/bandit_.png
    - assets/images/avatar.png
    - assets/images/